db:
  image: mysql
  ports:
    - "3306"
  environment:
    MYSQL_DATABASE: laravel
    MYSQL_ROOT_PASSWORD: 123456

web:
  build: .
  command: php -S 0.0.0.0:8888 -t /myapp/public
  volumes:
    - .:/myapp
  ports:
    - "8888:8888"
  links:
    - db
