db:
  image: mysql
  ports:
    - "3306"
  environment:
    MYSQL_DATABASE: laravel
    MYSQL_ROOT_PASSWORD: 123456

web:
  build: .
  command: bash -c "echo updating composer... && composer --working-dir=/myapp update && echo installing dependencies.... && composer --working-dir=/myapp install && echo running migrations... &&  php /myapp/artisan --force migrate && echo db:seed..... && php /myapp/artisan --force db:seed && echo starting php server... &&  php -S 0.0.0.0:8888 -t /myapp/public"
  volumes:
    - .:/myapp
  ports:
    - "8888:8888"
  links:
    - db
